name: EKS Deployment

on:
  workflow_run:
    workflows: ["Docker Build for Docker Hub"]
    types:
      - completed

jobs:
  k8deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Codebase Repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Update EKS kubeconfig
      run: aws eks update-kubeconfig --name tfcluster --region us-west-1

    - name: Create namespace if it doesn't exist
      run: |
        kubectl get namespace web || kubectl create namespace web

    - name: Apply httpd Deployment
      run: kubectl apply -f httpd-deployment.yaml
      working-directory: 6/kubernetes/httpd

    - name: Apply httpd loadbalancer Service
      run: kubectl apply -f httpd-loadbalancer-service.yaml
      working-directory: 6/kubernetes/httpd

    - name: Apply nginx Deployment
      run: kubectl apply -f nginx-deployment.yaml
      working-directory: 6/kubernetes/nginx

    - name: Apply nginx loadbalancer Service
      run: kubectl apply -f nginx-loadbalancer-service.yaml
      working-directory: 6/kubernetes/nginx